---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - rm -f Gemfile.lock
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 4.0" CHECK="test" PARALLEL_TEST_PROCESSORS=12
  - rvm: 2.4.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK="test_with_coveralls"
  - rvm: 2.5.0
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK="test_with_coveralls"
  - rvm: 2.4.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK="rubocop"
  - rvm: 2.4.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK="build" DEPLOY_TO_FORGE=yes
  - rvm: 2.4.3
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04
    script: 'bundle exec rspec spec/acceptance/php56_spec.rb'
    services: docker
    sudo: require
  - rvm: 2.4.3
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04
    script: 'bundle exec rspec spec/acceptance/php56_spec.rb'
    services: docker
    sudo: require
  - rvm: 2.4.3
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
    script: 'bundle exec rspec spec/acceptance/php56_spec.rb'
    services: docker
    sudo: require
  - rvm: 2.4.3
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-8
    script: 'bundle exec rspec spec/acceptance/php56_spec.rb'
    services: docker
    sudo: require
  - rvm: 2.4.3
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04
    script: 'bundle exec rspec spec/acceptance/php_spec.rb'
    services: docker
    sudo: require
  - rvm: 2.4.3
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04
    script: 'bundle exec rspec spec/acceptance/php_spec.rb'
    services: docker
    sudo: require
  - rvm: 2.4.3
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
    script: 'bundle exec rspec spec/acceptance/php_spec.rb'
    services: docker
    sudo: require
  - rvm: 2.4.3
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-8
    script: 'bundle exec rspec spec/acceptance/php_spec.rb'
    services: docker
    sudo: require
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-9 CHECK=beaker
    services: docker
    sudo: require
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "GOhttACuJt+3s38m4WnW5RuTgwqaAoeEQnNT+X1Ukn7KdcIk4KV8NzYU/CC0VIm8lUOnBWYJKEC4ixX/J/4Wbxox2RAoKMQrO++L0DB1zTCJnq9SfoUBMaQhXvLu+PbxAR0p3P47ozra0C+pOWDpOaxT9ecufrPQt9W9Z4aY/bs="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
